#!/bin/bash
# Stage Wine's codepage tables (c_*.nls) into the app bundle's nls folder.
#
# The app bundles four codepages by hand (c_437, c_1252, c_20127, c_28591) and
# ships everything else's lookup as a file that does not exist: a game that
# asks ntdll for a codepage such as c_949 (Korean) or c_932 (Japanese) gets
# STATUS_OBJECT_NAME_NOT_FOUND back from the NLS section path, which stalls
# locale setup instead of degrading. The complete set lives in the Wine build
# tree (`wine/build-macos/nls/*.nls`), generated by the same `make` that built
# the headers. This copies every table that build produced into the bundle's
# `nls/` folder, which the Xcode project ships as a folder reference -- so
# adding a file here is enough for it to reach the device, with no project edit.
#
# Best-effort by design: the archive check below can pass without a Wine build
# tree (a cache restore, a machine with pre-built libs), and a missing source
# must not fail the package. It reports what it found and exits 0 either way.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/app/Madeira/nls"
WINE_BUILD="$ROOT/wine/build-macos"

mkdir -p "$DEST"

# Where the tables can come from, in the order we prefer them. A full Wine
# build emits them under build-macos/nls; the source tree itself does not carry
# generated .nls files.
sources=("$WINE_BUILD/nls")

# If configure produced a build tree but the nls directory has not been made
# yet, ask for just that target. Wine's top-level Makefile has an `nls`
# subdirectory target, so this builds the tables without a full `make all`.
# Only attempted when the build tree exists and is configured.
if [[ -d "$WINE_BUILD" && -f "$WINE_BUILD/config.status" && ! -d "${sources[0]}" ]]; then
    echo "stage-nls: no $WINE_BUILD/nls yet; building the nls target."
    JOBS="${JOBS:-${BUILD_JOBS:-4}}"
    if make -C "$WINE_BUILD" -j"$JOBS" nls 2>&1 | tail -n 20; then
        :
    else
        echo "stage-nls: WARNING -- 'make nls' failed; keeping the committed tables only." >&2
    fi
fi

copied=0
missing=0
for src in "${sources[@]}"; do
    [[ -d "$src" ]] || continue
    for f in "$src"/*.nls; do
        [[ -f "$f" ]] || continue
        name="$(basename "$f")"
        # Codepages are the gap this exists to close; copy every one. The other
        # tables (locale, l_intl, norm*, sortdefault) are already committed, but
        # refresh them too when the build is newer -- harmless and self-healing.
        cp -f "$f" "$DEST/$name"
        copied=$((copied + 1))
    done
done

if [[ "$copied" -gt 0 ]]; then
    echo "stage-nls: staged $copied NLS table(s) into app/Madeira/nls/"
else
    echo "stage-nls: no NLS tables found under $WINE_BUILD/nls; using the committed set."
fi

# Report the codepage count that will actually ship, so a silent under-provision
# shows up in the build log rather than as a device-only failure later.
count=$(find "$DEST" -maxdepth 1 -name 'c_*.nls' | wc -l | tr -d ' ')
echo "stage-nls: $count codepage table(s) now in app/Madeira/nls/"
